### ISSUE TITLE
设备连接不上

### ISSUE THREAD

**Issue by caoanqi** [thisfeng/NSDNettyDemo#1]
两台android设备，一个安装client 一个安装server，发现无法进行连接和通信。
如果是一台设备安装了两端是可以的，都是在一个局域网内。
请问是什么问题？

**Comment by thisfeng** [comment]
仔细检查相互间是如何配置地址的那块代码

**Comment by caoanqi** [comment]
代码未进行过改动，调试比较两种情况，并未发现什么区别。如有什么特别的设置，能否贴下代码。谢谢
